### PR TITLE
Documenting how to use

### PR DESCRIPTION
**Pull request by hKQwHW**
WIP changes that need to be added upon and merged later

(sorry for accidentally making a messy commit with @Gomez0015 as the co-author, I messed up my Git settings and had to squash a previous commit by him together so that I wouldn't have a few duplicates of myself as a co-author)

### CODE REVIEW

**Review by Gomez0015 — APPROVED** [review]
Perfect, thanka for the help! and the enter submit bug fix!

**Comment by hKQwHW** [comment]
The submit bug fix was one of your commits that I ended up squashing into mine so that I didn't have multiple co-authors that were duplicates of myself (I'm very bad at using Git).

**Review by hKQwHW — COMMENTED** [review]
.gitignore should probably be kept, it needs to ignore node_modules and .env

**Comment by Gomez0015** [comment]
Yeah sorry trying to figure out how pull requests work ahahahha

**Comment by hKQwHW** [comment]
Lol, don't worry, it's fine

**Comment by hKQwHW** [comment]
Closing to re-create, I broke git

**Pull request closed without merging**
